# Generated by Django 3.0.3 on 2020-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='FGchPr89M7wgPyvHBxxP8y', max_length=255, primary_key=True, serialize=False),
        ),
    ]
