# Generated by Django 3.0.3 on 2020-07-16 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200716_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('15a67cc0-c377-425a-8d5a-59b31648a156'), max_length=255, primary_key=True, serialize=False),
        ),
    ]
