# Generated by Django 3.0.3 on 2020-07-21 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_unit', models.CharField(max_length=10)),
                ('min_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retail_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('min_wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wholesale_unit', models.CharField(max_length=10)),
                ('added_on', models.IntegerField(blank=True, null=True)),
                ('last_updated_on', models.IntegerField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_added', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_last_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
