# Generated by Django 3.0.3 on 2020-07-16 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b1223800-8847-44bb-86a6-af4bb61f233f'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('purchase_price', models.FloatField()),
                ('purchase_unit', models.CharField(max_length=10)),
                ('min_retail_price', models.FloatField()),
                ('max_retail_price', models.FloatField()),
                ('retail_unit', models.CharField(max_length=10)),
                ('min_wholesale_price', models.FloatField()),
                ('max_wholesale_price', models.FloatField()),
                ('wholesale_unit', models.CharField(max_length=10)),
                ('added_on', models.IntegerField()),
                ('last_updated_on', models.IntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_added', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_last_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
