# Generated by Django 3.0.3 on 2020-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='ASgLZqdkABRGvPPAVP85JD', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
