# Generated by Django 3.0.3 on 2020-07-16 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200716_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=uuid.UUID('338efc94-e163-415f-8bec-275321d3de1a'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
